# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Chen Yufei
description: Chen Yufei's homepage.
baseurl: ""
url: "https://yufei-chen-tj.github.io"
og_image: /assets/img/profile-pic.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching
    - name: Activities

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yufeichen@tongji.edu.cn
    - type: address
      value: "Room 437, Zhixin Building, Tongji University (Jiading Campus)"
      link: "https://j.map.baidu.com/48/zdUJ"
    - type: wechat
      value: Yufei TJ
      link: "#"
  

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
